Traceback (most recent call last):
  File "/home/gareth/miniconda3/envs/env_lisa_ew/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/gareth/miniconda3/envs/env_lisa_ew/lib/python3.10/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/gareth/miniconda3/envs/env_lisa_ew/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/home/gareth/miniconda3/envs/env_lisa_ew/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/gareth/miniconda3/envs/env_lisa_ew/lib/python3.10/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/gareth/miniconda3/envs/env_lisa_ew/lib/python3.10/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/gareth/miniconda3/envs/env_lisa_ew/lib/python3.10/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Grab important data from the dictionary

times_before = [0.5, 1, 4, 7, 14]
snrs = {
    'optimistic':{t: [] for t in times_before},
    'pessimistic':{t: [] for t in times_before},
    'cutoff':{t: [] for t in times_before},
}

fit_thresholds = {}
alpha = {}
sig_alpha = {}
rate_above = {}
psds = []

for results in search_results_all:
    psd = results['psd_type']
    print(psd)
    psds.append(psd)
    for t in times_before:
        snrs[psd][t] = results['nonoise'][str(t)]
    fit_thresholds[psd] = results['fit_threshold']
    alpha[psd] = results['alpha']
    sig_alpha[psd] = results['alpha_err']
    rate_above[psd] = results['rate_above']
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[7], line 17[0m
[1;32m     14[0m psds [38;5;241m=[39m []
[1;32m     16[0m [38;5;28;01mfor[39;00m results [38;5;129;01min[39;00m search_results_all:
[0;32m---> 17[0m     psd [38;5;241m=[39m [43mresults[49m[43m[[49m[38;5;124;43m'[39;49m[38;5;124;43mpsd_type[39;49m[38;5;124;43m'[39;49m[43m][49m
[1;32m     18[0m     [38;5;28mprint[39m(psd)
[1;32m     19[0m     psds[38;5;241m.[39mappend(psd)

[0;31mTypeError[0m: string indices must be integers

